### ISSUE TITLE
Support Self-Hosted API Documentation In Spring Boot Applications

### ISSUE THREAD

**Issue by kurron** [wilkinsona/spring-restdocs#12]
I'm using Spring Boot 1.2.1, Spring REST Docs 0.1.0.BUILD-SNAPSHOT and Gradle 2.2.1.  I love what docs gives us but I was disappointed to see that due to the task ordering of the build, I wasn't easily able to embed the API docs into my application and make them self-hosted.  I've worked around the issue by updating the JAR after asciidoc is run but I'm hoping we can come up with a more elegant solution.  Perhaps we can work with someone on the Boot team and figure out a lifecycle that allow for self-hosting?

Here is my solution, if anybody finds that interesting.

```
asciidoctor {
    attributes 'generated': generatedDocumentation
    inputs.dir generatedDocumentation
    dependsOn integrationTests
}

task copyApiDocs( type: Copy, dependsOn: asciidoctor ) {
    from "${buildDir}/asciidoc/html5"
    into "${buildDir}/api-docs/static/api-docs/"
}

task updateJarWithApiDocumentation( dependsOn: copyApiDocs ) {
    doLast {
        ant.jar( update: 'true',
                 duplicate: 'fail',
                 compress: 'false',
                 destfile: "${libsDir}/${archivesBaseName}-${version}.jar") {
            fileset( dir: "${buildDir}/api-docs" )
        }
    }
}
```

**Comment by Pytry** [comment]
Would something like this be appropriate for a "boot-starter" or Gradle plugin perhaps?

**Comment by wilkinsona** [comment]
Thanks, @kurron. I'd had self-hosting in mind but had yet to investigate.

I'm a member of the Boot team so I'm sure we can work something out. That said, I don't think any changes should be necessary on the Boot side.

IIRC, Gradle runs the tests after it's built the jar, however that ordering can be changed by updating task dependencies. It might even be sufficient to set the Asciidoctor's output dir as an input for the jar task. Some experimentation to figure out the best way is probably in order.

In the project's early days there was a Gradle plugin but I removed it along with some Gradle-centric assumptions as part of making things work more nicely with Maven. Depending on how complicated the configuration becomes, it may be time to revisit that decision.

**Comment by wilkinsona** [comment]
This seems to be a nice concise way to configure a Gradle build to include the documentation as static content that'll be served by Spring Boot:

```groovy
jar {
	dependsOn asciidoctor
	from ("${asciidoctor.outputDir}/html5") {
		into 'static/docs'
	}
}
```

The Maven equivalent requires binding the the Asciidoctor plugin to the `prepare-package` phase and then configuring the resources plugin to copy over the documentation:

```xml
<plugin>
	<artifactId>maven-resources-plugin</artifactId>
	<version>2.7</version>
	<executions>
		<execution>
			<id>copy-resources</id>
			<phase>prepare-package</phase>
			<goals>
				<goal>copy-resources</goal>
			</goals>
			<configuration>
				<outputDirectory>${project.build.outputDirectory}/static/docs</outputDirectory>
				<resources>
					<resource>
						<directory>${project.build.directory}/generated-docs</directory>
					</resource>
				</resources>
			</configuration>
		</execution>
	</executions>
</plugin>
```
