### ISSUE TITLE
Publish snapshots to repo.spring.io

### ISSUE THREAD

**Issue by jhiemer** [wilkinsona/spring-restdocs#5]
https://repo.spring.io/libs-snapshot/org/springframework/

**Comment by wilkinsona** [comment]
Am I right in thinking that this is a slightly cryptic request for snapshots to be published to repo.spring.io?

**Comment by jhiemer** [comment]
Yes, that would be awesome, as I am really interested to test spring-restdocs.

**Comment by krosangit** [comment]
I second this request. Manually putting this in our corporate nexus works but it would be much easier if it would be in a public repo such as the spring or mavencentral repo.

**Comment by jhiemer** [comment]
thx @wilkinsona.

**Comment by krosangit** [comment]
Awesome! Thanks for the effort @wilkinsona.
We will be using this in our new architecture.
