### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tsweets** [wilkinsona/spring-restdocs#8]
I get this error when trying to compile the samples. 
You probably forgot to check something into github
Happens with maven and gradle.

[ERROR] /home/tsweets/projects/spring-restdocs/rest-notes-spring-data-rest/src/test/java/com/example/notes/ApiDocumentation.java:[98,81] incompatible types: org.springframework.restdocs.core.LinkDescriptor cannot be converted to org.springframework.restdocs.core.LinkExtractor

 **Environment**
Arch Linux
Oracle Java 1.8

**Comment by wilkinsona** [comment]
It works fine for me and, more importantly, on the CI server. It looks like you're trying to compile against and older snapshot that doesn't contain [this commit](https://github.com/wilkinsona/spring-restdocs/commit/cae7e3fb582d024f924943828b6721494610730f).

**Comment by tsweets** [comment]
Doesn't look like the repo has the latest code
https://repo.spring.io/snapshot/org/springframework/restdocs/spring-restdocs-core/0.1.0.BUILD-SNAPSHOT/

Last version is from 1/8 which is before your commit. 
That's why the compile is failing on my side, its grabbing an older restdocs-core.

--Tony

**Comment by wilkinsona** [comment]
Looks like Artifactory's in a mess. The new code was there, but it's failing to increment the snapshot properly as part of the deploy so the old code's preferred over the new. I've deleted the snapshots and associated Maven metadata in the hope that a clean slate will sort things out.
