### ISSUE TITLE
Can't resolve snapshot from repo.spring.io

### ISSUE THREAD

**Issue by beccagaspard** [wilkinsona/spring-restdocs#9]
Looks like something might be wrong with the snapshot published to repo.spring.io?  
I'm getting this error when I try to run the quickstart examples:

>Could not resolve all dependencies for configuration ':testCompile'.
> Artifact 'org.springframework.restdocs:spring-restdocs-core:0.1.0.BUILD-SNAPSHOT:spring-restdocs-core.jar' not found.
  Searched in the following locations:
      https://repo.spring.io/snapshot/org/springframework/restdocs/spring-restdocs-core/0.1.0.BUILD-SNAPSHOT/spring-restdocs-core-0.1.0.BUILD-20150113.124005-2.jar

I was able to work around by `gradle install`-ing spring-restdocs-core myself, but it might be confusing for people trying to run the examples.

**Comment by wilkinsona** [comment]
Thanks. There's something wrong with Artifactory's snapshot publishing. I've cleared out the old snapshots and published a new build. It appears to have solved the problem (for now at least), You may need to run a build with `--refresh-dependencies` for Gradle to pick them up.
